import { RoomData, ReviewData } from "./types"

export const rooms: RoomData[] = [
  {
    id: 1,
    type: "deluxe",
    name: "Deluxe Ocean Room",
    badge: "Deluxe",
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400",
    bed: "King Bed",
    sqm: "38 m²",
    rating: 4.8,
    reviews: 312,
    amenities: ["Ocean View", "AC", "WiFi", "Minibar"],
    price: 320,
    originalPrice: 410,
    availability: "available",
    availabilityText: "Available",
  },
  {
    id: 2,
    type: "suite",
    name: "Premium Suite",
    badge: "Suite",
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=400",
    bed: "King Bed",
    sqm: "55 m²",
    rating: 4.9,
    reviews: 187,
    amenities: ["Ocean View", "Terrace", "Bathtub", "Butler"],
    price: 580,
    originalPrice: 720,
    availability: "low",
    availabilityText: "3 rooms left",
  },
  {
    id: 3,
    type: "villa",
    name: "Garden Villa",
    badge: "Villa",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=400",
    bed: "Twin Beds",
    sqm: "42 m²",
    rating: 4.7,
    reviews: 241,
    amenities: ["Garden View", "Private Pool", "AC", "Spa"],
    price: 450,
    originalPrice: 560,
    availability: "available",
    availabilityText: "Available",
  },
  {
    id: 4,
    type: "overwater",
    name: "Overwater Bungalow",
    badge: "Overwater",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=400",
    bed: "King Bed",
    sqm: "72 m²",
    rating: 5.0,
    reviews: 98,
    amenities: ["Overwater", "Glass Floor", "Butler", "Shower"],
    price: 1200,
    originalPrice: 1500,
    availability: "critical",
    availabilityText: "1 room left",
  },
  {
    id: 5,
    type: "deluxe",
    name: "Deluxe Lagoon Room",
    badge: "Deluxe",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=400",
    bed: "Queen Bed",
    sqm: "35 m²",
    rating: 4.6,
    reviews: 309,
    amenities: ["Lagoon View", "AC", "WiFi", "Balcony"],
    price: 290,
    originalPrice: 380,
    availability: "available",
    availabilityText: "Available",
  },
  {
    id: 6,
    type: "suite",
    name: "Family Suite",
    badge: "Suite",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400",
    bed: "2 King Beds",
    sqm: "80 m²",
    rating: 4.8,
    reviews: 156,
    amenities: ["Ocean View", "Kids Area", "Pool", "2 Baths"],
    price: 750,
    originalPrice: 900,
    availability: "low",
    availabilityText: "2 rooms left",
  },
  {
    id: 7,
    type: "villa",
    name: "Beach Pool Villa",
    badge: "Villa",
    image: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=400",
    bed: "King Bed",
    sqm: "95 m²",
    rating: 4.9,
    reviews: 72,
    amenities: ["Beachfront", "Private Pool", "Dining", "Butler"],
    price: 1800,
    originalPrice: null,
    availability: "available",
    availabilityText: "Available",
  },
  {
    id: 8,
    type: "suite",
    name: "Honeymoon Suite",
    badge: "Suite",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=400",
    bed: "King Bed",
    sqm: "65 m²",
    rating: 5.0,
    reviews: 44,
    amenities: ["Ocean View", "Jacuzzi", "Rose Setup", "Champagne"],
    price: 950,
    originalPrice: 1100,
    availability: "critical",
    availabilityText: "1 room left",
  },
]

export const reviews: ReviewData[] = [
  {
    id: 1,
    name: "Sarah M.",
    rating: 5.0,
    gradient: "bg-gradient-to-br from-[#f093fb] to-[#f5576c]",
    initials: "SM",
    date: "Dec 2024",
    room: "Overwater Bungalow",
    review:
      "Absolutely breathtaking. The overwater bungalow exceeded every expectation. Waking up to the lagoon below the glass floor is surreal.",
    helpful: 24,
  },
  {
    id: 2,
    name: "James K.",
    rating: 4.8,
    gradient: "bg-gradient-to-br from-[#4facfe] to-[#00f2fe]",
    initials: "JK",
    date: "Nov 2024",
    room: "Premium Suite",
    review:
      "The staff anticipates your every need before you even realize it. The spa treatments and beach service were world-class.",
    helpful: 18,
  },
  {
    id: 3,
    name: "Priya L.",
    rating: 5.0,
    gradient: "bg-gradient-to-br from-[#43e97b] to-[#38f9d7]",
    initials: "PL",
    date: "Oct 2024",
    room: "Honeymoon Suite",
    review:
      "We stayed for our honeymoon and they surprised us with rose petals and champagne every evening. Truly magical and unforgettable.",
    helpful: 31,
  },
  {
    id: 4,
    name: "David R.",
    rating: 4.9,
    gradient: "bg-gradient-to-br from-[#fa709a] to-[#fee140]",
    initials: "DR",
    date: "Sep 2024",
    room: "Beach Pool Villa",
    review:
      "Best resort in the Maldives, no contest. The food at the overwater restaurant alone is worth the trip. Will return next year.",
    helpful: 12,
  },
]
